### ISSUE TITLE
Different phones

### ISSUE THREAD

**Issue by shubhamchaudhary** [carts-uiet/bus_boarding_paper#7]
Show graphs with data from different phones. We need to show that our algo works the same with different manufacturers

###### TODO
- [x] Collect data for different manufactures
- [x] Find accuracies for different data sets
- [x] Add graph/table in paper

##### Acceptance Criterion
- [ ] A graph/table that depicts that our algo gives consistent results with different phones

**Comment by shubhamchaudhary** [comment]
Added acceptance criterion

**Comment by tanjot** [comment]
Need stair climbing data from 2 more phones

**Comment by tanjot** [comment]
Made the graph, find apt. place in paper to place it

**Comment by shubhamchaudhary** [comment]
put graph in figures

**Comment by tanjot** [comment]
Added graph
